export enum Permissions {
  DocumentUpload = "DocumentUpload",
  DocumentDownload = "DocumentDownload",
  DocumentSearch = "DocumentSearch",
  CreateNewFolder = "CreateNewFolder",
  DownloadLog = "DownloadLog",
  CreateNewQA = "CreateNewQA",
  DeleteQA = "DeleteQA",
  EditQA = "EditQA",
  ViewQA = "ViewQA",
  EditSettings = "EditSettings",
  AddTaskAndDueDate = "AddTaskAndDueDate",
  DeleteTask = "DeleteTask",
  EditTask = "EditTask",
  InviteParticipatesGlobally = "InviteParticipatesGlobally",
  InviteParticipates = "InviteParticipates",
  AddDeleteTeam = "AddDeleteTeam",
  RemoveParticipatesGlobally = "RemoveParticipatesGlobally",
  RemoveParticipate = "RemoveParticipate",
}
